name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run base workflow
        uses: ./.github/actions/base
        with:
          go-version: '1.24'

      - name: Build homoglyph
        run: bash ./build.sh glyph.txt

      - name: Build homoglitch
        run: bash ./build.sh glitch.txt

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: ./build/*
